#!/bin/bash
rm $2
nohup python $1 1 >  $2 &
nohup python $1 2 >> $2 &
nohup python $1 3 >> $2 &
nohup python $1 4 >> $2 &
nohup python $1 5 >  $2 &
nohup python $1 6 >> $2 &
nohup python $1 7 >> $2 &
nohup python $1 8 >> $2 &
python $1 9
